import React,{useState}from"react";
import{HeartPulse,ShieldCheck,LayoutDashboard,Building2,Network,Brain,Activity,Users,Settings,LogOut,Bell,UserRound,Stethoscope,ClipboardList,Info,ChevronRight,Menu,X,Hospital,UserCheck}from"lucide-react";

const roles={Admin:["Admin","System Administrator"],Hospital:["Hospital / Client","Hospital Client"],User:["User / Patient","Patient Portal"]};
const hospitals=[
 {id:"HOSP-001",name:"City Heart Hospital",status:"Connected",training:"Completed"},
 {id:"HOSP-002",name:"Apollo Care Center",status:"Training",training:"In progress"},
 {id:"HOSP-003",name:"Unity Medical",status:"Connected",training:"Completed"}
];

function Login({login}){const[r,setR]=useState("Admin");return <div className="login"><section className="hero"><div className="brand"><span><HeartPulse/></span><div><b>Heart Disease FL</b><small>Privacy-Preserving AI</small></div></div><div className="heroText"><label><ShieldCheck size={14}/> Privacy-preserving healthcare AI</label><h1>Collaborative intelligence.<em>Private by design.</em></h1><p>Frontend GUI prototype for heart disease prediction using Federated Learning.</p><div className="flow"><i>Local Training</i><ChevronRight/><i>Model Update</i><ChevronRight/><i>Global Model</i></div></div><div className="privacy"><ShieldCheck/><div><b>Your data is protected</b><small>Raw patient data remains local in this frontend prototype.</small></div></div></section><section className="loginRight"><form className="loginCard" onSubmit={e=>{e.preventDefault();login(r)}}><div className="loginIcon"><HeartPulse/></div><h2>Welcome Back!</h2><p>Sign in to continue to your portal.</p><label>Username or Email</label><input placeholder="Enter username or email" defaultValue="demo"/><label>Password</label><input type="password" placeholder="Enter password" defaultValue="demo"/><label>Login as</label><select value={r} onChange={e=>setR(e.target.value)}><option value="Admin">Admin</option><option value="Hospital">Hospital / Client</option><option value="User">User / Patient</option></select><button className="primary">LOGIN <ChevronRight size={17}/></button><button className="link" type="button">Forgot Password?</button><small className="demo">Frontend demo — connect authentication later.</small></form></section></div>}

function Shell({role,page,setPage,logout,children}){const[open,setOpen]=useState(false);const menus=role==="Admin"?[
 ["dashboard","Dashboard",LayoutDashboard],["hospitals","Hospitals",Building2],["fl","FL Monitoring",Network],["model","Global Model",Brain],["performance","Performance",Activity],["users","Users",Users],["settings","Settings",Settings]
]:role==="Hospital"?[
 ["dashboard","Dashboard",LayoutDashboard],["training","Local Training",Activity],["updates","Model Updates",Network],["fl","FL Activity",Network],["model","Global Model",Brain],["settings","Settings",Settings]
]:[
 ["dashboard","Dashboard",LayoutDashboard],["prediction","Prediction",HeartPulse],["history","Prediction History",ClipboardList],["about","About Project",Info],["profile","Profile",UserRound],["settings","Settings",Settings]
];return <div className="app"><aside className={open?"side open":"side"}><div className="sideBrand"><div className="brandIcon"><HeartPulse size={19}/></div><div><b>Heart Disease FL</b><small>Frontend GUI</small></div><button className="close" onClick={()=>setOpen(false)}><X/></button></div><div className="role"><UserRound size={15}/><div><b>{roles[role][0]}</b><small>{roles[role][1]}</small></div></div><nav>{menus.map(([id,name,Icon])=><button key={id} className={page===id?"nav active":"nav"} onClick={()=>{setPage(id);setOpen(false)}}><Icon size={17}/>{name}</button>)}</nav><button className="nav logout" onClick={logout}><LogOut size={17}/>Logout</button></aside><main><header><button className="hamb" onClick={()=>setOpen(true)}><Menu/></button><div><small>HEALTHCARE AI PLATFORM</small><h1>{pageTitle(role,page)}</h1></div><div className="top"><Bell size={18}/><div className="avatar"><UserRound size={16}/></div><b>{roles[role][0]}</b></div></header><div className="content">{children}</div></main></div>}

function pageTitle(role,p){const m={dashboard:role==="Admin"?"Admin Dashboard":role==="Hospital"?"Hospital Dashboard":"Patient Dashboard",hospitals:"Hospitals",fl:"FL Monitoring",model:"Global Model",performance:"Model Performance",users:"Users",settings:"Settings",training:"Local Training",updates:"Model Updates",prediction:"Heart Disease Prediction",history:"Prediction History",about:"About Project",profile:"Patient Profile"};return m[p]||"Dashboard"}

function Stats(){return <div className="stats"><Stat icon={Building2} label="Total Hospitals" value="3" note="Participating clients" c="blue"/><Stat icon={Users} label="Active Clients" value="3" note="Current round" c="purple"/><Stat icon={Network} label="Current FL Round" value="05" note="Communication round" c="orange"/><Stat icon={Brain} label="Global Model" value="Ready" note="Latest version" c="green"/></div>}
function Stat({icon:I,label,value,note,c}){return <div className="stat"><div className={"statIcon "+c}><I size={18}/></div><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></div>}

function AdminPage({page,setPage}){if(page==="hospitals")return <HospitalList setPage={setPage}/>;if(page==="fl")return <Monitoring/>;if(page==="model")return <Model/>;if(page==="performance")return <Performance/>;if(page==="users")return <UsersPage/>;if(page==="settings")return <SettingsPage/>;return <><Head title="Overview" text="Monitor hospitals, Federated Learning rounds, and the global model."/><Stats/><div className="grid"><Panel title="Hospital / Client Status" sub="Current participation in active round"><table><thead><tr><th>Client</th><th>Hospital</th><th>Status</th><th>Round 05</th></tr></thead><tbody>{hospitals.map(h=><tr key={h.id}><td><b>{h.id}</b></td><td>{h.name}</td><td className={h.status==="Training"?"orange":"green"}>● {h.status}</td><td>{h.training}</td></tr>)}</tbody></table></Panel><Panel title="Federated Learning Progress" sub="Local Training → Model Update → FedAvg → Global Model"><Workflow/></Panel></div><div className="grid"><PerformanceCard/><Panel title="Recent Activity" sub="Latest system events"><ul className="activity"><li>● HOSP-001 completed local training</li><li>● HOSP-002 is training</li><li>● Model update received</li></ul></Panel></div></>}

function HospitalList({setPage}){return <><Head title="Hospitals" text="Select an individual hospital to view its detailed client dashboard."/><div className="hospitalCards">{hospitals.map(h=><div className="hospitalCard" key={h.id}><div className="hospitalIcon"><Hospital/></div><div><span>{h.id}</span><h3>{h.name}</h3><p className={h.status==="Training"?"orange":"green"}>● {h.status}</p><small>Training: {h.training}</small></div><button onClick={()=>setPage("hospital-"+h.id)}>View Hospital <ChevronRight size={16}/></button></div>)}</div></>}

function HospitalDetail({id,setPage}){const h=hospitals.find(x=>x.id===id)||hospitals[0];return <><Head title={h.name} text={`${h.id} • Individual Hospital / Client Dashboard`}/><button className="back" onClick={()=>setPage("hospitals")}>← Back to Hospitals</button><div className="stats"><Stat icon={Hospital} label="Hospital ID" value={h.id} note={h.name} c="blue"/><Stat icon={Network} label="FL Round" value="05" note="Active round" c="purple"/><Stat icon={Activity} label="Training" value={h.training} note="Local status" c="green"/><Stat icon={Brain} label="Global Model" value="Ready" note="Latest version" c="orange"/></div><div className="grid"><Panel title="Individual Hospital FL Workflow" sub="Only model updates leave the hospital"><Workflow/></Panel><Panel title="Hospital Activity" sub="Recent events"><ul className="activity"><li>● Local training completed</li><li>● Model update prepared</li><li>● Waiting for FedAvg aggregation</li></ul></Panel></div></>}

function Workflow(){return <div className="workflow">{["Local Training","Model Update","FedAvg","Global Model"].map((x,i)=><React.Fragment key={x}><div className="step"><b>{i+1}</b><strong>{x}</strong><small>{i<2?"Completed":"Pending"}</small></div>{i<3&&<ChevronRight/>}</React.Fragment>)}</div>}
function Head({title,text}){return <div className="head"><div><h2>{title}</h2><p>{text}</p></div><span className="ok">● System online</span></div>}
function Panel({title,sub,children}){return <section className="panel"><h3>{title}</h3><p>{sub}</p>{children}</section>}
function PerformanceCard(){return <Panel title="Global Model Performance" sub="Sample presentation data"><div className="metrics">{[["Accuracy","92.4%"],["Precision","90.8%"],["Recall","91.6%"],["F1-Score","90.2%"]].map(x=><div className="metric" key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><div className="bar"><i style={{width:x[1]}}/></div></div>)}</div></Panel>}
function Monitoring(){return <><Head title="FL Monitoring" text="Monitor the current Federated Learning communication round."/><Stats/><Panel title="Round 05 Monitoring" sub="Client progress"><Workflow/></Panel></>}
function Model(){return <><Head title="Global Model" text="Global model version and aggregation status."/><div className="grid"><Panel title="Current Global Model" sub="Latest aggregated model"><div className="bigStatus">READY</div><p>Model version: FL-v0.5</p><p>Last aggregation: Round 04</p></Panel><Panel title="FedAvg Aggregation" sub="Next aggregation status"><div className="progress"><b>2 / 3 client updates received</b><div className="bar"><i style={{width:"67%"}}/></div></div></Panel></div></>}
function Performance(){return <><Head title="Model Performance" text="Evaluation metrics for the latest global model."/><PerformanceCard/><div className="grid"><Panel title="Metric Comparison" sub="Accuracy, Precision, Recall and F1-score"><div className="chart">{[92.4,90.8,91.6,90.2].map((v,i)=><div key={v}><i style={{height:v+"%"}}/><b>{v}%</b><small>{["Accuracy","Precision","Recall","F1"][i]}</small></div>)}</div></Panel><Panel title="Evaluation Note" sub="For presentation/demo data"><div className="privacy"><ShieldCheck/><div><b>Sample UI metrics</b><small>Replace these values with actual evaluation results after model training.</small></div></div></Panel></div></>}
function UsersPage(){return <><Head title="Users" text="Frontend user overview."/><div className="userList">{["Patient A","Patient B","Patient C","Hospital Client Admin"].map((x,i)=><div key={x}><UserCheck/><b>{x}</b><small>{i===3?"Hospital administrator":"Patient user"}</small><span className="ok">Active</span></div>)}</div></>}
function SettingsPage(){return <><Head title="Settings" text="Frontend settings screen."/><Panel title="System Settings" sub="Demo-only configuration"><div className="settingsRows"><label>Notifications <input type="checkbox" defaultChecked/></label><label>Privacy protection <input type="checkbox" defaultChecked/></label><label>Dark mode <input type="checkbox"/></label></div></Panel></>}

function HospitalPage({page,setPage}){if(page==="training")return <><Head title="Local Training" text="Hospital-side local model training."/><Panel title="Training Progress" sub="Training remains local"><div className="bigStatus">100%</div><div className="bar"><i style={{width:"100%"}}/></div><div className="privacy"><ShieldCheck/><div><b>Patient data stays local</b><small>Only model updates are intended to be shared.</small></div></div></Panel></>;if(page==="updates")return <><Head title="Model Updates" text="Prepare and review the local model update."/><Panel title="Model Update" sub="Round 05"><div className="bigStatus">READY</div><button className="primary">Submit Model Update</button></Panel></>;if(page==="fl")return <><Head title="FL Activity" text="Hospital participation in Federated Learning."/><Panel title="Round 05" sub="Current workflow"><Workflow/></Panel></>;if(page==="model")return <Model/>;if(page==="settings")return <SettingsPage/>;return <><Head title="Hospital Overview" text="Your individual hospital dashboard."/><div className="stats"><Stat icon={Hospital} label="Hospital ID" value="HOSP-001" note="City Heart Hospital" c="blue"/><Stat icon={Network} label="FL Round" value="05" note="Active round" c="purple"/><Stat icon={Activity} label="Training" value="Done" note="Local training" c="green"/><Stat icon={Brain} label="Global Model" value="Ready" note="Latest model" c="orange"/></div><div className="grid"><Panel title="Federated Learning Workflow" sub="Raw patient data stays at the hospital"><Workflow/></Panel><Panel title="Recent Activity" sub="Individual client events"><ul className="activity"><li>● Local training completed</li><li>● Model update prepared</li><li>● Waiting for global aggregation</li></ul></Panel></div></>}

function UserPage({page}){if(page==="prediction"||page==="dashboard")return <UserPrediction/>;if(page==="history")return <><Head title="Prediction History" text="Previous frontend prediction records."/><Panel title="Prediction History" sub="Demo records"><table><thead><tr><th>Date</th><th>Result</th><th>Status</th></tr></thead><tbody><tr><td>22 Aug 2026</td><td>Not Detected</td><td className="green">Completed</td></tr><tr><td>18 Aug 2026</td><td>Detected</td><td className="green">Completed</td></tr></tbody></table></Panel></>;if(page==="about")return <><Head title="About Project" text="Learn about the privacy-preserving Federated Learning concept."/><Panel title="About Heart Disease FL" sub="Frontend prototype"><p>Hospitals can conceptually train locally while a global model is formed from model updates rather than raw patient records.</p></Panel></>;if(page==="profile")return <><Head title="Patient Profile" text="Individual patient profile screen."/><Panel title="Profile" sub="Demo information"><div className="profileBox"><UserRound/><div><b>Demo Patient</b><small>Patient ID: USER-001</small></div></div></Panel></>;return <SettingsPage/>}
function UserPrediction(){const[r,setR]=useState("");return <><Head title="Heart Disease Prediction" text="Enter patient features for a frontend demonstration."/><div className="userGrid"><section className="panel"><h3>Patient Information</h3><p>Enter prediction features.</p><form className="form">{["Age","Sex","Chest Pain Type","Resting Blood Pressure","Cholesterol","Maximum Heart Rate","Smoking","Exercise-Induced Angina"].map(x=><label key={x}>{x}<input placeholder={"Enter "+x.toLowerCase()}/></label>)}<button className="primary" onClick={e=>{e.preventDefault();setR("Demo result: prediction interface is ready.")}}> <Stethoscope/> Predict Heart Disease</button></form></section><section className="result"><div className="loginIcon"><HeartPulse/></div><h2>Prediction Result</h2><p>{r||"Submit patient information to display the prediction result."}</p><div className="resultBox">{r?"Heart Disease: Awaiting real model":"Awaiting input"}</div><small><ShieldCheck/> Patient data is protected. Frontend demo only.</small></section></div></>}

export default function App(){const[role,setRole]=useState(null);const[page,setPage]=useState("dashboard");const login=r=>{setRole(r);setPage("dashboard")};const logout=()=>{setRole(null);setPage("dashboard")};if(!role)return <Login login={login}/>;let content;if(role==="Admin"){content=page.startsWith("hospital-")?<HospitalDetail id={page.replace("hospital-","")} setPage={setPage}/>:<AdminPage page={page} setPage={setPage}/>;}else if(role==="Hospital")content=<HospitalPage page={page} setPage={setPage}/>;else content=<UserPage page={page}/>;return <Shell role={role} page={page} setPage={setPage} logout={logout}>{content}</Shell>}
